//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MomsMedicalHistory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clinic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clinic()
        {
            this.clinical_visits = new HashSet<clinical_visits>();
        }
    
        public int clinic_ID { get; set; }
        public string clinic_name { get; set; }
        public int clinic_type_ID { get; set; }
        public string clinic_phone { get; set; }
        public string clinic_address { get; set; }
        public int city_ID { get; set; }
        public int state_ID { get; set; }
        public int zipcode_ID { get; set; }
    
        public virtual city city { get; set; }
        public virtual clinic_types clinic_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clinical_visits> clinical_visits { get; set; }
        public virtual state state { get; set; }
        public virtual zipcode zipcode { get; set; }
    }
}
