//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MomsMedicalHistory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hospital_visits
    {
        public int hospital_visit_ID { get; set; }
        public int hospital_info_ID { get; set; }
        public System.DateTime hospital_visit_date { get; set; }
        public string hospital_visit_reason { get; set; }
        public int hospital_attending_physician_ID { get; set; }
        public string hospital_visit_discharge_direction { get; set; }
        public string hospital_diagnosis { get; set; }
        public Nullable<bool> hospital_wasAdmitted { get; set; }
        public string hospital_co_insurer { get; set; }
    
        public virtual hospital hospital { get; set; }
        public virtual physician physician { get; set; }
    }
}
