//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MomsMedicalHistory.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Medical_MachineEntities : DbContext
    {
        public Medical_MachineEntities()
            : base("name=Medical_MachineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<allergic_medications> allergic_medications { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<clinic_types> clinic_types { get; set; }
        public virtual DbSet<clinical_visits> clinical_visits { get; set; }
        public virtual DbSet<clinic> clinics { get; set; }
        public virtual DbSet<facility_types> facility_types { get; set; }
        public virtual DbSet<general_medications> general_medications { get; set; }
        public virtual DbSet<hospital_departments> hospital_departments { get; set; }
        public virtual DbSet<hospital_visits> hospital_visits { get; set; }
        public virtual DbSet<hospital> hospitals { get; set; }
        public virtual DbSet<medical_conditions> medical_conditions { get; set; }
        public virtual DbSet<medicine_dosage_units> medicine_dosage_units { get; set; }
        public virtual DbSet<medicine_forms> medicine_forms { get; set; }
        public virtual DbSet<medicine_strength_units> medicine_strength_units { get; set; }
        public virtual DbSet<pharmacy> pharmacies { get; set; }
        public virtual DbSet<physician_specialties> physician_specialties { get; set; }
        public virtual DbSet<physician_visits> physician_visits { get; set; }
        public virtual DbSet<physician> physicians { get; set; }
        public virtual DbSet<prescription_medication_interactions> prescription_medication_interactions { get; set; }
        public virtual DbSet<prescription_medications> prescription_medications { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<therapeutic_facilities> therapeutic_facilities { get; set; }
        public virtual DbSet<therapy_visit_types> therapy_visit_types { get; set; }
        public virtual DbSet<therapy_visits> therapy_visits { get; set; }
        public virtual DbSet<vitamin> vitamins { get; set; }
        public virtual DbSet<zipcode> zipcodes { get; set; }
    }
}
