//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MomsMedicalHistory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medical_conditions
    {
        public int medical_condition_ID { get; set; }
        public string medical_condition { get; set; }
        public System.DateTime medical_condition_diagnosis_date { get; set; }
        public int medical_condition_diagnosing_doctor_ID { get; set; }
    
        public virtual physician physician { get; set; }
    }
}
