//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MomsMedicalHistory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pharmacy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pharmacy()
        {
            this.prescription_medications = new HashSet<prescription_medications>();
        }
    
        public int pharmacy_ID { get; set; }
        public string pharmacy_name { get; set; }
        public string pharmacy_phone { get; set; }
        public string pharmacy_address { get; set; }
        public int city_ID { get; set; }
        public int state_ID { get; set; }
        public int zipcode_ID { get; set; }
    
        public virtual city city { get; set; }
        public virtual state state { get; set; }
        public virtual zipcode zipcode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prescription_medications> prescription_medications { get; set; }
    }
}
