//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MomsMedicalHistory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class physician
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public physician()
        {
            this.clinical_visits = new HashSet<clinical_visits>();
            this.hospital_visits = new HashSet<hospital_visits>();
            this.hospitals = new HashSet<hospital>();
            this.medical_conditions = new HashSet<medical_conditions>();
            this.physician_visits = new HashSet<physician_visits>();
            this.prescription_medications = new HashSet<prescription_medications>();
            this.therapy_visits = new HashSet<therapy_visits>();
        }
    
        public int physician_ID { get; set; }
        public int physician_specialty_ID { get; set; }
        public string physician_phone { get; set; }
        public string physician_lastname { get; set; }
        public string physician_firstname { get; set; }
        public string physician_address { get; set; }
        public int city_ID { get; set; }
        public int state_ID { get; set; }
        public int zipcode_ID { get; set; }
    
        public virtual city city { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clinical_visits> clinical_visits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hospital_visits> hospital_visits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hospital> hospitals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medical_conditions> medical_conditions { get; set; }
        public virtual physician_specialties physician_specialties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<physician_visits> physician_visits { get; set; }
        public virtual state state { get; set; }
        public virtual zipcode zipcode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prescription_medications> prescription_medications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<therapy_visits> therapy_visits { get; set; }
    }
}
