//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MomsMedicalHistory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class physician_visits
    {
        public int physician_visit_ID { get; set; }
        public int physician_info_ID { get; set; }
        public System.DateTime physician_visit_date { get; set; }
        public System.TimeSpan physician_visit_time { get; set; }
        public string physician_visit_blood_pressure { get; set; }
        public int physician_visit_weight { get; set; }
        public int physician_visit_temperature { get; set; }
        public string physician_visit_reason { get; set; }
        public string physician_visit_result { get; set; }
        public string physician_visit_note { get; set; }
    
        public virtual physician physician { get; set; }
    }
}
