//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MomsMedicalHistory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prescription_medication_interactions
    {
        public int prescription_medicine_interaction_ID { get; set; }
        public int general_medicine_ID { get; set; }
        public int medicine_ID { get; set; }
    
        public virtual general_medications general_medications { get; set; }
        public virtual prescription_medications prescription_medications { get; set; }
    }
}
