//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MomsMedicalHistory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class therapy_visits
    {
        public int therapy_visit_ID { get; set; }
        public int therapy_info_ID { get; set; }
        public System.DateTime therapy_visit_date { get; set; }
        public System.TimeSpan therapy_visit_time { get; set; }
        public int therapy_visit_type_ID { get; set; }
        public Nullable<decimal> therapy_visit_fee { get; set; }
        public int therapy_referring_doctor_ID { get; set; }
    
        public virtual physician physician { get; set; }
        public virtual therapeutic_facilities therapeutic_facilities { get; set; }
        public virtual therapy_visit_types therapy_visit_types { get; set; }
    }
}
