//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MomsMedicalHistory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vitamin
    {
        public int vitamin_ID { get; set; }
        public string vitamin_name { get; set; }
        public int medicine_dosage_ID { get; set; }
        public int medicine_dosage { get; set; }
        public int medicine_strength_ID { get; set; }
        public int medicine_strength { get; set; }
    
        public virtual medicine_dosage_units medicine_dosage_units { get; set; }
        public virtual medicine_strength_units medicine_strength_units { get; set; }
    }
}
